<?php

declare(strict_types=1);

namespace Drupal\dc_form\Plugin\GraphQLCompose\EntityType;

use Drupal\graphql_compose\Plugin\GraphQLCompose\GraphQLComposeEntityTypeBase;
use GraphQL\Type\Definition\ObjectType;
use GraphQL\Type\Definition\Type;

/**
 * GraphQL Compose entity-type plugin for `contact_form`.
 *
 * Registers the ContactForm GraphQL object type plus a top-level
 * `contactForm(id: ID!)` query, mirroring the pattern
 * `graphql_compose_menus` uses for menus.
 *
 * For now we expose the form's identity and recipients only — those
 * resolve cleanly through graphql_compose's built-in machinery. The
 * per-field metadata (field types, labels, required flags) is
 * already available to consumers via `paragraphForm.fields[]` on the
 * paragraph itself, which is the make-side mirror of the form's
 * structure. Surfacing the contact_message bundle's field config as
 * a top-level type is a phase-2 nice-to-have that needs custom
 * SchemaType wiring beyond the base annotation pattern.
 *
 * @GraphQLComposeEntityType(
 *   id = "contact_form",
 *   base_fields = {
 *     "id" = {
 *       "type_sdl" = "ID",
 *       "required" = TRUE,
 *       "description" = @Translation("Machine name of the contact form (e.g. 'make_xxx_yyy')."),
 *     },
 *     "label" = {
 *       "type_sdl" = "String",
 *       "required" = TRUE,
 *       "description" = @Translation("Human-readable form name."),
 *     },
 *     "recipients" = {
 *       "type_sdl" = "String",
 *       "multiple" = TRUE,
 *       "required" = TRUE,
 *       "description" = @Translation("Email addresses Drupal sends submissions to."),
 *     },
 *   },
 * )
 */
class ContactForm extends GraphQLComposeEntityTypeBase {

  /**
   * {@inheritdoc}
   *
   * Add a top-level `contactForm(id: ID!): ContactForm` query so
   * consumers can fetch a form by machine name without needing to
   * traverse from a paragraph.
   */
  public function registerTypes(): void {
    parent::registerTypes();

    $extension = new ObjectType([
      'name' => 'Query',
      'fields' => fn() => [
        'contactForm' => [
          'type' => $this->gqlSchemaTypeManager->get('ContactForm'),
          'description' => (string) $this->t('Load a ContactForm by its machine name.'),
          'args' => [
            'id' => [
              'type' => Type::nonNull(Type::id()),
              'description' => (string) $this->t('Contact form machine name. Forms generated by make.decoupled.io are prefixed `make_`.'),
            ],
          ],
        ],
      ],
    ]);

    $this->gqlSchemaTypeManager->extend($extension);
  }

}
